# Generated by Django 2.2.7 on 2019-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(max_length=200)),
                ('allergyCodes', models.CharField(max_length=200)),
                ('allergicFoods', models.CharField(max_length=200)),
                ('img', models.URLField()),
            ],
        ),
    ]
